### PR TITLE
Rough attempt at adding Ubuntu 20.04 support

### PR DESCRIPTION
**Pull request by ad0nis**
Several weeks ago, I had taken a crack at adding support for Ubuntu 20.04. While my attempt was mostly unsuccessful, I didn't want to toss the code completely. Spent some time today re-merging changes. I understand if this gets rejected, as it is not a complete fix, and could create the perception of supporting 20.04 when SO isn't ready for that just yet.

### CODE REVIEW

**Comment by TOoSmOotH** [comment]
Were you able to run 20.04 and successfully install it?

**Comment by ad0nis** [comment]
I just swapped out CPUs in my SO-to-be box last night. Will be re-formatting after work today, and then will re-attempt, and tell you how it goes with this update. If it goes like last time, the install script will finish execution, but there will have been setup errors. End result is that the SO server appears to be up and online with a web interface that can't be logged into successfully, and it's active enough on the network that my pi-hole reported it as the second-loudest talker on my network, so it's clearly doing something, even if I can't see what that something is. :D  I assume that there are more tweaks that will be required.  Will post setup errors when I get that far.

**Comment by ad0nis** [comment]
Machine check errors on the replacement CPUs means I might not be able to test this out as quickly as I had intended. Will circle back when I can.

**Comment by TOoSmOotH** [comment]
Closing due to inactivity

**Pull request closed without merging**
