### PR TITLE
Bugfix/so-scripts

### PR DESCRIPTION
**Pull request by lan94**
Hi,

two small bugfixes for two so-scripts that i noticed the last days:

**so-features-enable**

In my latest install of Security Onion 2.3 the version variable in global.sls was set to '2.3.0' (including single quotes). Because of that the script tries to download the images, e.g. so-logstash:'2.3.0'-features. This dont work. In order to get this to work I added a second `sed` to remove these single quotes.

**so-firewall**

In line 115 the script expects an args array with length of 1 and checks this. But in line 119 the script tries to get args[1] which is position 2 of the array. This needs to be changed to args[0] for position 1. The next function addportgroup works the same but is doing this right.

Kind regards
Lukas

### CODE REVIEW

**Comment by TOoSmOotH** [comment]
@lan94  Any possible way you can do a PR to dev and close this one out?

**Comment by lan94** [comment]
Hi @TOoSmOotH, thanks for your feedback. I changed base to dev, was this right or do I need to create a whole new PR ?

**Comment by TOoSmOotH** [comment]
No this is correct. Don't need a new PR.

**Comment by TOoSmOotH** [comment]
Couple of things.. We need commits to be signed otherwise I can't merge.

In so-features-enable, we have a common function that won't require sed fu.
VERSION=$(lookup_pillar soversion) If you want to make that change and sign your commits I can merge.

**Comment by m0duspwnens** [comment]
@lan94 Thanks for the bug report. We have made the changes and merged them into the dev branch. This will be resolved in the next release.

**Pull request closed without merging**
