### PR TITLE
add user password update command

### PR DESCRIPTION
**Pull request by Ron89**
To help resolving #4455.

Added password resetting tool for TheHive based on their API documented on http://docs.thehive-project.org/thehive/legacy/thehive3/api/user/

Added password resetting tool for Fleet based on MySQL commands.

### CODE REVIEW

**Review by jertel — DISMISSED** [review]
Thanks for contributing this script!

**Comment by jertel** [comment]
Looks like you didn't sign the commit. We can't merge commits unless they're signed. You can read more about signing commits with git via a google search.

**Comment by Ron89** [comment]
OK, while I am at it, let me also add the fleet password update as suggested here https://github.com/Security-Onion-Solutions/securityonion/discussions/4455#discussioncomment-848335 , just for completion sake.

**Comment by Ron89** [comment]
While adding the password updating script for fleet, I noticed that mysql won't report exception even when we are updating the row that doesn't exist, even though the updating command for the non-existent row won't change anything. As a result, the negative case for `so-fleet-user-update` is ineffective. In example: if user `meow@kitten.org` does not exist. Calling
```
so-fleet-user-update meow@kitten.org
```
then provide password in STDIN will result in normal return. However, it does not actually change the users table.

Since the fleet password update script is using the same mechanism as `so-fleet-user-enable`, the negative case is equally ineffective for that script. In example: if user `meow@kitten.org` does not exist. Calling
```
so-fleet-user-enable meow@kitten.org TRUE
```
will result in script reporting `Successfully updated user in Fleet`. However, no change is made for the users table.

Should this be reported as a separate issue? I don't think it is a big problem. But it does make this set of scripts less reliable for further automation (such as merging the two script's functionality into `so-user update`).

**Comment by jertel** [comment]
We've not invested a lot of time into these scripts because there are some roadmap uncertainties on the future of how we integrate case management and network device management into Security Onion. So yes, there is room for improvement but at the same time we'd trying to spend our limited resources on areas that have more short term clarity. So your assistance in improving these scripts in the meantime is very appreciated.

If we want to error out when UPDATEs don't find a record we could first run a `SELECT count(1) FROM users WHERE username='$FLEET_USER'` and check that the response is != 0. But, as you mentioned, there is really nothing that is being done to recover from a missing user. Another temporary option is to change the text from "Successfully updated user in Fleet" to "User has been updated if it exists", to at least avoid communicating inaccurate information.

If you're up for any of these changes, feel free to jump in. Again, thank you!

**Comment by Ron89** [comment]
Negative case fixed. If user doesn't exist, or if database corruption happens and multiple hits for the target user presents, the script will report the error and return `-2` exit code.

**Comment by jertel** [comment]
Did you set the +x bit on those new scripts? I believe all the other files in that dir are set with the execute bit.

**Comment by Ron89** [comment]
Yes, they are...

```
-rwxr-xr-x 1 chong chong 1.8K Aug 15 07:25 salt/common/tools/sbin/so-thehive-user-update
-rwxr-xr-x 1 chong chong 2.4K Aug 15 07:25 salt/common/tools/sbin/so-fleet-user-update
```

**Review by jertel — APPROVED** [review]

**Pull request merged**
