### PR TITLE
Add ASN annotation for IP

### PR DESCRIPTION
**Pull request by datlife**
Related Issue (or Feature?): https://github.com/Security-Onion-Solutions/securityonion/issues/5068

### CODE REVIEW

**Comment by datlife** [comment]
@TOoSmOotH Hi Mike, not sure if you are the right person to tag. Feel free to let me know if this feature is aligned with SO roadmap. Thanks

**Review by TOoSmOotH — CHANGES_REQUESTED** [review]
This needs to be signed in order for me to accept it

**Comment by weslambert** [comment]
@datlife , please ensure this is commit signed so we can accept the PR.

**Comment by datlife** [comment]
Thanks @weslambert and @TOoSmOotH for the reminder!

I did not know about the GPG signing thing :D. Glad I learned something new today.

**Review by TOoSmOotH — APPROVED** [review]

**Pull request merged**
