### PR TITLE
Update import-evtx-logs.json

### PR DESCRIPTION
**Pull request by chateaulav**
version updates to match 2.4 release pipelines related to #11889

### CODE REVIEW

**Comment by chateaulav** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chateaulav** [comment]
recheck

**Comment by chateaulav** [comment]
recheck

**Review by dougburks — APPROVED** [review]

**Comment by dougburks** [comment]
Thanks @chateaulav !

**Pull request merged**
