### PR TITLE
fix descriptions in files related to analyzers

### PR DESCRIPTION
**Pull request by security-companion**
Hi,
I noticed some copy-paste errors in files related to analyzers and fixed them.
Is it possible to merge this?
Greetings
security-companion

### CODE REVIEW

**Comment by security-companion** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by TOoSmOotH** [comment]
@weslambert Do you see any issues with merging this?

**Comment by weslambert** [comment]
Looks good to me.

**Review by TOoSmOotH — DISMISSED** [review]

**Comment by TOoSmOotH** [comment]
@security-companion You need to sign this commit before I can merge it.

**Review by TOoSmOotH — APPROVED** [review]

**Pull request merged**
